# This file created by conda-build 3.25.0
# ------------------------------------------------

package:
  name: cryptography
  version: 41.0.3
source:
  sha256: bc8427b5f09417108297b3f50b5f52f8e84ee6ebc2f073d83ffec4d39896c271
  url: https://github.com/pyca/cryptography/archive/refs/tags/41.0.3.tar.gz
build:
  number: 0
  script:
    - export OPENSSL_DIR=$PREFIX
    - python -m pip install . -vv
  string: py310h34e2850_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - _sysroot_linux-aarch64_curr_repodata_hack 4 h57d6b7b_13
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_impl_linux-aarch64 2.40 h40ea8b1_0
    - binutils_linux-aarch64 2.40 h19b5abf_1
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2023.7.22 hbcca054_0
    - cffi 1.15.1 py310h255011f_3
    - cross-python_linux-aarch64 3.10 40_cpython
    - crossenv 1.4.0 pyhd8ed1ab_0
    - gcc_impl_linux-64 12.3.0 he2b93b0_0
    - gcc_impl_linux-aarch64 12.3.0 hfb0b921_0
    - gcc_linux-aarch64 12.3.0 hd570763_1
    - kernel-headers_linux-64 2.6.32 he073ed8_16
    - kernel-headers_linux-aarch64 4.18.0 h5b4a56d_13
    - ld_impl_linux-64 2.40 h41732ed_0
    - ld_impl_linux-aarch64 2.40 hc365e21_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-devel_linux-64 12.3.0 h8bca6fd_0
    - libgcc-devel_linux-aarch64 12.3.0 h1a07b91_0
    - libgcc-ng 13.1.0 he5830b7_0
    - libgomp 13.1.0 he5830b7_0
    - libiconv 1.17 h166bdaf_0
    - libnsl 2.0.0 h7f98852_0
    - libsanitizer 12.3.0 h0f45ef3_0
    - libsqlite 3.42.0 h2797004_0
    - libstdcxx-ng 13.1.0 hfd8a6a1_0
    - libuuid 2.38.1 h0b41bf4_0
    - libzlib 1.2.13 hd590300_5
    - lz4-c 1.9.4 hcb278e6_0
    - ncurses 6.4 hcb278e6_0
    - openssl 3.1.2 hd590300_0
    - popt 1.16 h0b475e3_2002
    - pycparser 2.21 pyhd8ed1ab_0
    - python 3.10.12 hd12c33a_0_cpython
    - python_abi 3.10 3_cp310
    - readline 8.2 h8228510_1
    - rsync 3.2.7 h70740c4_0
    - rust 1.70.0 h70c747d_0
    - rust-std-aarch64-unknown-linux-gnu 1.70.0 ha15b78c_0
    - rust-std-x86_64-unknown-linux-gnu 1.70.0 hc1431ca_0
    - rust_linux-aarch64 1.70.0 h54ed21c_0
    - sed 4.8 he412f7d_0
    - sysroot_linux-64 2.12 he073ed8_16
    - sysroot_linux-aarch64 2.17 h5b4a56d_13
    - tk 8.6.12 h27826a3_0
    - tzdata 2023c h71feb2d_0
    - xxhash 0.8.0 h7f98852_3
    - xz 5.2.6 h166bdaf_0
    - zstd 1.5.2 hfc55251_7
  host:
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hf897c2e_4
    - ca-certificates 2023.7.22 hcefe29a_0
    - cffi 1.15.1 py310hf0c4615_3
    - ld_impl_linux-aarch64 2.40 h2d8c526_0
    - libffi 3.4.2 h3557bc0_5
    - libgcc-ng 13.1.0 h2b4548d_0
    - libgomp 13.1.0 h2b4548d_0
    - libnsl 2.0.0 hf897c2e_0
    - libsqlite 3.42.0 h194ca79_0
    - libuuid 2.38.1 hb4cce97_0
    - libzlib 1.2.13 h31becfc_5
    - ncurses 6.4 h2e1726e_0
    - openssl 3.1.2 h31becfc_0
    - pip 23.2.1 pyhd8ed1ab_0
    - pycparser 2.21 pyhd8ed1ab_0
    - python 3.10.12 hbbe8eec_0_cpython
    - python_abi 3.10 3_cp310
    - readline 8.2 h8fc344f_1
    - semantic_version 2.10.0 pyhd8ed1ab_0
    - setuptools 68.0.0 pyhd8ed1ab_0
    - setuptools-rust 1.6.0 pyhd8ed1ab_0
    - tk 8.6.12 hd8af866_0
    - typing_extensions 4.7.1 pyha770c72_0
    - tzdata 2023c h71feb2d_0
    - wheel 0.41.1 pyhd8ed1ab_0
    - xz 5.2.6 h9cdd2b7_0
  run:
    - cffi >=1.12
    - libgcc-ng >=12
    - openssl >=3.1.2,<4.0a0
    - python >=3.10,<3.11.0a0
    - python >=3.10,<3.11.0a0 *_cpython
    - python_abi 3.10.* *_cp310
test:
  commands:
    - pytest
  imports:
    - cryptography
    - cryptography.fernet
    - cryptography.hazmat
    - cryptography.hazmat.backends
    - cryptography.hazmat.backends.openssl
    - cryptography.hazmat.bindings
    - cryptography.hazmat.bindings.openssl
    - cryptography.hazmat.primitives
    - cryptography.hazmat.primitives.asymmetric
    - cryptography.hazmat.primitives.ciphers
    - cryptography.hazmat.primitives.kdf
    - cryptography.hazmat.primitives.twofactor
    - cryptography.x509
  requires:
    - cryptography-vectors 41.0.3.*
    - hypothesis
    - iso8601
    - pretend
    - pytest
    - pytest-benchmark
    - pytest-subtests
    - pytz
  source_files:
    - pyproject.toml
    - tests
about:
  description: 'cryptography is a package which provides cryptographic recipes and

    primitives to Python developers. Our goal is for it to be your

    "cryptographic standard library". It supports Python 3.6+ and PyPy3 7.2+.

    cryptography includes both high level recipes and low level interfaces

    to common cryptographic algorithms such as symmetric ciphers, message

    digests, and key derivation functions..

    '
  dev_url: https://github.com/pyca/cryptography
  doc_source_url: https://github.com/pyca/cryptography/blob/main/docs/index.rst
  doc_url: https://cryptography.io/en/latest
  home: https://cryptography.io
  license: Apache-2.0 AND BSD-3-Clause AND PSF-2.0 AND MIT
  license_family: BSD
  license_file: LICENSE
  summary: cryptography is a package designed to expose cryptographic primitives and
    recipes to Python developers.
extra:
  copy_test_source_files: true
  feedstock-name: cryptography
  final: true
  recipe-maintainers:
    - h-vetinari
    - jakirkham
    - ocefpaf
