# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Mar  1 20:18:39 2022
# ------------------------------------------------

package:
  name: keyutils
  version: 1.6.1
source:
  patches:
    - 0001-Make-endian-detection-in-work-on-non-RHEL-distributi.patch
    - 0002-Fix-installing-shared-library-symlinks-with-DESTDIR.patch
  sha256: c8b15722ae51d95b9ad76cc6d49a4c2cc19b0c60f72f61fb9bf43eea7cbd64ce
  url: https://people.redhat.com/~dhowells/keyutils/keyutils-1.6.1.tar.bz2
build:
  number: '0'
  run_exports:
    - keyutils >=1.6.1,<2.0a0
  string: h4e544f5_0
requirements:
  build:
    - _openmp_mutex 4.5 1_gnu
    - binutils_impl_linux-aarch64 2.36.1 h026399b_2
    - binutils_linux-aarch64 2.36 h7854541_6
    - file 5.39 h5b764c4_0
    - gcc_impl_linux-aarch64 10.3.0 ha07e0e6_12
    - gcc_linux-aarch64 10.3.0 h4e3e293_6
    - kernel-headers_linux-aarch64 4.18.0 h5b4a56d_13
    - ld_impl_linux-aarch64 2.36.1 h02ad14f_2
    - libgcc-devel_linux-aarch64 10.3.0 h8e480ec_12
    - libgcc-ng 11.2.0 hf1cc4e7_12
    - libgomp 11.2.0 hf1cc4e7_12
    - libmagic 5.39 hd8af866_0
    - libsanitizer 10.3.0 h971684a_12
    - libstdcxx-ng 11.2.0 h0d0a5bb_12
    - libzlib 1.2.11 hb9de7d4_1013
    - make 4.3 h309ac5b_1
    - sysroot_linux-aarch64 2.17 h43d7e78_13
    - zlib 1.2.11 hb9de7d4_1013
  host:
    - _openmp_mutex 4.5 1_gnu
    - libgcc-ng 11.2.0 hf1cc4e7_12
    - libgomp 11.2.0 hf1cc4e7_12
  run:
    - libgcc-ng >=10.3.0
test:
  commands:
    - test -f ${PREFIX}/lib/libkeyutils.so
    - keyctl --version | grep '1.6.1'
about:
  description: 'Keyutils is a set of utilities for managing the key retention facility
    in

    the kernel, which can be used by filesystems, block devices and more to

    gain and retain the authorization and encryption keys required to perform

    secure operations.

    '
  home: https://people.redhat.com/~dhowells/keyutils/
  license: LGPL-2.1-or-later
  license_file: LICENCE.LGPL
  summary: Linux Key Management Utilities
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - chrisburr
