# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Oct 15 08:33:15 2023
# ------------------------------------------------

package:
  name: libnsl
  version: 2.0.1
source:
  sha256: 59048b53be8d3904bf939313debf13956a881b0de79da40f7719a77bcd1e9c53
  url: https://github.com/thkukuk/libnsl/archive/v2.0.1.tar.gz
build:
  number: '0'
  run_exports:
    - libnsl >=2.0.1,<2.1.0a0
  string: h31becfc_0
requirements:
  build:
    - _openmp_mutex 4.5 2_gnu
    - _sysroot_linux-aarch64_curr_repodata_hack 4 h57d6b7b_13
    - binutils_impl_linux-aarch64 2.40 h870a726_0
    - binutils_linux-aarch64 2.40 h94bbfa1_2
    - gcc_impl_linux-aarch64 12.3.0 hcde2664_2
    - gcc_linux-aarch64 12.3.0 h464a8f7_2
    - gnuconfig 2020.11.07 hd8ed1ab_0
    - kernel-headers_linux-aarch64 4.18.0 h5b4a56d_13
    - ld_impl_linux-aarch64 2.40 h2d8c526_0
    - libgcc-devel_linux-aarch64 12.3.0 h8b5ab12_2
    - libgcc-ng 13.2.0 hf8544c7_2
    - libgomp 13.2.0 hf8544c7_2
    - libsanitizer 12.3.0 h8ebda82_2
    - libstdcxx-ng 13.2.0 h9a76618_2
    - libtool 2.4.7 h4de3ea5_0
    - make 4.3 h309ac5b_1
    - pkg-config 0.29.2 hb9de7d4_1008
    - sysroot_linux-aarch64 2.17 h5b4a56d_13
  host:
    - _openmp_mutex 4.5 2_gnu
    - libgcc-ng 13.2.0 hf8544c7_2
    - libgomp 13.2.0 hf8544c7_2
  run:
    - libgcc-ng >=12
test:
  commands:
    - test -f ${PREFIX}/lib/libnsl.so
about:
  home: https://github.com/thkukuk/libnsl
  license: LGPL-2.1-only
  license_family: GPL
  license_file: COPYING
  summary: Public client interface library for NIS(YP)
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - isuruf
    - izahn
    - xhochy
