# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Oct 31 11:13:22 2023
# ------------------------------------------------

package:
  name: ncurses
  version: '6.4'
source:
  fn: ncurses-6.4.tar.gz
  sha256: 6931283d9ac87c5073f30b6290c4c75f21632bb4fc3603ac8100812bed248159
  url: http://ftp.gnu.org/pub/gnu/ncurses/ncurses-6.4.tar.gz
build:
  ignore_run_exports:
    - libcxx
    - libstdcxx-ng
  number: '2'
  run_exports:
    - ncurses >=6.4,<7.0a0
  string: h0425590_2
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - _sysroot_linux-aarch64_curr_repodata_hack 4 h57d6b7b_13
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_impl_linux-aarch64 2.40 h40ea8b1_0
    - binutils_linux-aarch64 2.40 h19b5abf_2
    - coreutils 9.4 hd590300_0
    - gcc_impl_linux-64 12.3.0 he2b93b0_2
    - gcc_impl_linux-aarch64 12.3.0 hfb0b921_2
    - gcc_linux-aarch64 12.3.0 hd570763_2
    - gxx_impl_linux-64 12.3.0 he2b93b0_2
    - gxx_impl_linux-aarch64 12.3.0 hfb0b921_2
    - gxx_linux-aarch64 12.3.0 h4913bc6_2
    - kernel-headers_linux-64 2.6.32 he073ed8_16
    - kernel-headers_linux-aarch64 4.18.0 h5b4a56d_13
    - ld_impl_linux-64 2.40 h41732ed_0
    - ld_impl_linux-aarch64 2.40 hc365e21_0
    - libgcc-devel_linux-64 12.3.0 h8bca6fd_2
    - libgcc-devel_linux-aarch64 12.3.0 h1a07b91_2
    - libgcc-ng 13.2.0 h807b86a_2
    - libgomp 13.2.0 h807b86a_2
    - libsanitizer 12.3.0 h0f45ef3_2
    - libstdcxx-devel_linux-64 12.3.0 h8bca6fd_2
    - libstdcxx-devel_linux-aarch64 12.3.0 h1a07b91_2
    - libstdcxx-ng 13.2.0 h7e041cc_2
    - libtool 2.4.7 h27087fc_0
    - make 4.3 hd18ef5c_1
    - ncurses
    - pkg-config 0.29.2 h36c2ea0_1008
    - sysroot_linux-64 2.12 he073ed8_16
    - sysroot_linux-aarch64 2.17 h5b4a56d_13
  host:
    - _openmp_mutex 4.5 2_gnu
    - libgcc-ng 13.2.0 hf8544c7_2
    - libgomp 13.2.0 hf8544c7_2
    - libstdcxx-ng 13.2.0 h9a76618_2
  run:
    - libgcc-ng >=12
test:
  commands:
    - test ! -f ${PREFIX}/lib/libncurses.a
    - test ! -f ${PREFIX}/lib/libncursesw.a
    - test -f ${PREFIX}/lib/libncurses.so
    - test -f ${PREFIX}/lib/libncursesw.so
    - test ! -f ${PREFIX}/lib/libtinfo.a
    - test ! -f ${PREFIX}/lib/libtinfow.a
    - test -f ${PREFIX}/lib/libtinfo.so
    - test -f ${PREFIX}/lib/libtinfow.so
    - test ! -f ${PREFIX}/lib/libform.a
    - test ! -f ${PREFIX}/lib/libformw.a
    - test -f ${PREFIX}/lib/libform.so
    - test -f ${PREFIX}/lib/libformw.so
    - test ! -f ${PREFIX}/lib/libmenu.a
    - test ! -f ${PREFIX}/lib/libmenuw.a
    - test -f ${PREFIX}/lib/libmenu.so
    - test -f ${PREFIX}/lib/libmenuw.so
    - test ! -f ${PREFIX}/lib/libpanel.a
    - test ! -f ${PREFIX}/lib/libpanelw.a
    - test -f ${PREFIX}/lib/libpanel.so
    - test -f ${PREFIX}/lib/libpanelw.so
    - test -d ${PREFIX}/include/ncurses
    - test -d ${PREFIX}/include/ncursesw
    - test -L ${PREFIX}/include/ncurses/curses.h
    - test -L ${PREFIX}/include/ncursesw/curses.h
    - test -f ${PREFIX}/include/curses.h
    - test -L ${PREFIX}/include/ncurses/cursesapp.h
    - test -L ${PREFIX}/include/ncursesw/cursesapp.h
    - test -f ${PREFIX}/include/cursesapp.h
    - test -L ${PREFIX}/include/ncurses/cursesf.h
    - test -L ${PREFIX}/include/ncursesw/cursesf.h
    - test -f ${PREFIX}/include/cursesf.h
    - test -L ${PREFIX}/include/ncurses/cursesm.h
    - test -L ${PREFIX}/include/ncursesw/cursesm.h
    - test -f ${PREFIX}/include/cursesm.h
    - test -L ${PREFIX}/include/ncurses/cursesp.h
    - test -L ${PREFIX}/include/ncursesw/cursesp.h
    - test -f ${PREFIX}/include/cursesp.h
    - test -L ${PREFIX}/include/ncurses/cursesw.h
    - test -L ${PREFIX}/include/ncursesw/cursesw.h
    - test -f ${PREFIX}/include/cursesw.h
    - test -L ${PREFIX}/include/ncurses/cursslk.h
    - test -L ${PREFIX}/include/ncursesw/cursslk.h
    - test -f ${PREFIX}/include/cursslk.h
    - test -L ${PREFIX}/include/ncurses/eti.h
    - test -L ${PREFIX}/include/ncursesw/eti.h
    - test -f ${PREFIX}/include/eti.h
    - test -L ${PREFIX}/include/ncurses/etip.h
    - test -L ${PREFIX}/include/ncursesw/etip.h
    - test -f ${PREFIX}/include/etip.h
    - test -L ${PREFIX}/include/ncurses/form.h
    - test -L ${PREFIX}/include/ncursesw/form.h
    - test -f ${PREFIX}/include/form.h
    - test -L ${PREFIX}/include/ncurses/menu.h
    - test -L ${PREFIX}/include/ncursesw/menu.h
    - test -f ${PREFIX}/include/menu.h
    - test -L ${PREFIX}/include/ncurses/nc_tparm.h
    - test -L ${PREFIX}/include/ncursesw/nc_tparm.h
    - test -f ${PREFIX}/include/nc_tparm.h
    - test -L ${PREFIX}/include/ncurses/ncurses.h
    - test -L ${PREFIX}/include/ncursesw/ncurses.h
    - test -f ${PREFIX}/include/ncurses.h
    - test -L ${PREFIX}/include/ncurses/ncurses_dll.h
    - test -L ${PREFIX}/include/ncursesw/ncurses_dll.h
    - test -f ${PREFIX}/include/ncurses_dll.h
    - test -L ${PREFIX}/include/ncurses/panel.h
    - test -L ${PREFIX}/include/ncursesw/panel.h
    - test -f ${PREFIX}/include/panel.h
    - test -L ${PREFIX}/include/ncurses/term.h
    - test -L ${PREFIX}/include/ncursesw/term.h
    - test -f ${PREFIX}/include/term.h
    - test -L ${PREFIX}/include/ncurses/term_entry.h
    - test -L ${PREFIX}/include/ncursesw/term_entry.h
    - test -f ${PREFIX}/include/term_entry.h
    - test -L ${PREFIX}/include/ncurses/termcap.h
    - test -L ${PREFIX}/include/ncursesw/termcap.h
    - test -f ${PREFIX}/include/termcap.h
    - test -L ${PREFIX}/include/ncurses/tic.h
    - test -L ${PREFIX}/include/ncursesw/tic.h
    - test -f ${PREFIX}/include/tic.h
    - test -L ${PREFIX}/include/ncurses/unctrl.h
    - test -L ${PREFIX}/include/ncursesw/unctrl.h
    - test -f ${PREFIX}/include/unctrl.h
    - test -f ${PREFIX}/lib/pkgconfig/form.pc
    - cat ${PREFIX}/lib/pkgconfig/form.pc
    - test -f ${PREFIX}/lib/pkgconfig/formw.pc
    - cat ${PREFIX}/lib/pkgconfig/formw.pc
    - test -f ${PREFIX}/lib/pkgconfig/menu.pc
    - cat ${PREFIX}/lib/pkgconfig/menu.pc
    - test -f ${PREFIX}/lib/pkgconfig/menuw.pc
    - cat ${PREFIX}/lib/pkgconfig/menuw.pc
    - test -f ${PREFIX}/lib/pkgconfig/ncurses++.pc
    - cat ${PREFIX}/lib/pkgconfig/ncurses++.pc
    - test -f ${PREFIX}/lib/pkgconfig/ncurses++w.pc
    - cat ${PREFIX}/lib/pkgconfig/ncurses++w.pc
    - test -f ${PREFIX}/lib/pkgconfig/ncurses.pc
    - cat ${PREFIX}/lib/pkgconfig/ncurses.pc
    - test -f ${PREFIX}/lib/pkgconfig/ncursesw.pc
    - cat ${PREFIX}/lib/pkgconfig/ncursesw.pc
    - test -f ${PREFIX}/lib/pkgconfig/panel.pc
    - cat ${PREFIX}/lib/pkgconfig/panel.pc
    - test -f ${PREFIX}/lib/pkgconfig/panelw.pc
    - cat ${PREFIX}/lib/pkgconfig/panelw.pc
    - test -f ${PREFIX}/lib/pkgconfig/tinfo.pc
    - cat ${PREFIX}/lib/pkgconfig/tinfo.pc
    - test -f ${PREFIX}/lib/pkgconfig/tinfow.pc
    - cat ${PREFIX}/lib/pkgconfig/tinfow.pc
    - pkg-config ncurses --libs
    - pkg-config ncurses --libs | grep "^-L${PREFIX}/lib .*-lncurses -ltinfo$"
    - pkg-config tinfo --libs | grep "^-L${PREFIX}/lib .*-ltinfo$"
    - pkg-config ncursesw --libs | grep "^-L${PREFIX}/lib .*-lncursesw -ltinfow$"
    - pkg-config tinfow --libs | grep "^-L${PREFIX}/lib .*-ltinfow$"
  requires:
    - pkg-config
about:
  description: 'The ncurses (new curses) library is a free software

    emulation of curses in System V Release 4.0 (SVr4),

    and more. It uses terminfo format, supports pads and

    color and multiple highlights and forms characters and

    function-key mapping, and has all the other SVr4-curses

    enhancements over BSD curses. SVr4 curses is better

    known today as X/Open Curses

    '
  dev_url: http://invisible-island.net/ncurses/
  doc_url: http://invisible-island.net/ncurses/NCURSES-Programming-HOWTO.html
  home: http://www.gnu.org/software/ncurses/
  license: X11 AND BSD-3-Clause
  license_file: COPYING
  summary: Library for text-based user interfaces
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - fhoehle
    - jakirkham
    - mingwandroid
