# This file created by conda-build 3.24.0
# ------------------------------------------------

package:
  name: libarchive
  version: 3.6.2
source:
  patches:
    - patches/0001-Add-lib-to-CMAKE_FIND_LIBRARY_PREFIXES-for-lzma.patch
    - patches/0003-VC9-compatibility-test-for-BCryptDeriveKeyPBKDF2.patch
    - patches/0004-VC9-compatibility-define-BCRYPT_SUCCESS.patch
    - patches/0006-VC-openssl-define-inline-as-__inline.patch
    - patches/0007-CMake-VC9-compatibility-ignore-some-warnings.patch
  sha256: 652b84588488c2ff38db8f666cd7f781163f85bff4449dcb2e16d3c734f96697
  url: https://github.com/libarchive/libarchive/archive/v3.6.2.tar.gz
build:
  number: 1
  run_exports:
    - libarchive >=3.6.2,<3.7.0a0
  string: h566b526_1
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - _sysroot_linux-aarch64_curr_repodata_hack 4 h57d6b7b_13
    - autoconf 2.71 pl5321h2b4cb7a_1
    - automake 1.16.5 pl5321ha770c72_0
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_impl_linux-aarch64 2.39 h57c828d_1
    - binutils_linux-aarch64 2.39 h9a81858_13
    - gcc_impl_linux-64 12.2.0 hcc96c02_19
    - gcc_impl_linux-aarch64 12.2.0 h74c8edf_19
    - gcc_linux-aarch64 12.2.0 hc1bb72a_13
    - kernel-headers_linux-64 2.6.32 he073ed8_15
    - kernel-headers_linux-aarch64 4.18.0 h5b4a56d_13
    - ld_impl_linux-64 2.40 h41732ed_0
    - ld_impl_linux-aarch64 2.39 hc438fd5_1
    - libgcc-devel_linux-64 12.2.0 h3b97bd3_19
    - libgcc-devel_linux-aarch64 12.2.0 hb41d4e8_19
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libnsl 2.0.0 h7f98852_0
    - libsanitizer 12.2.0 h46fd767_19
    - libstdcxx-ng 12.2.0 h46fd767_19
    - libtool 2.4.7 h27087fc_0
    - m4 1.4.18 h516909a_1001
    - make 4.3 hd18ef5c_1
    - perl 5.32.1 2_h7f98852_perl5
    - pkg-config 0.29.2 h36c2ea0_1008
    - sysroot_linux-64 2.12 he073ed8_15
    - sysroot_linux-aarch64 2.17 h5b4a56d_13
  host:
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hf897c2e_4
    - ca-certificates 2023.5.7 hcefe29a_0
    - icu 72.1 hcf00150_0
    - ld_impl_linux-aarch64 2.40 h2d8c526_0
    - libffi 3.4.2 h3557bc0_5
    - libgcc-ng 12.2.0 h607ecd0_19
    - libgomp 12.2.0 h607ecd0_19
    - libiconv 1.17 h9cdd2b7_0
    - libnsl 2.0.0 hf897c2e_0
    - libsqlite 3.42.0 h194ca79_0
    - libstdcxx-ng 12.2.0 hc13a102_19
    - libuuid 2.38.1 hb4cce97_0
    - libxml2 2.11.3 py310he2cb0cb_0
    - libzlib 1.2.13 h4e544f5_4
    - lz4-c 1.9.3 h01db608_1
    - lzo 2.10 h516909a_1000
    - ncurses 6.3 headf329_1
    - openssl 3.1.0 h31becfc_3
    - python 3.10.11 ha43d526_0_cpython
    - python_abi 3.10 3_cp310
    - readline 8.2 h8fc344f_1
    - tk 8.6.12 hd8af866_0
    - tzdata 2023c h71feb2d_0
    - xz 5.2.6 h9cdd2b7_0
    - zlib 1.2.13 h4e544f5_4
    - zstd 1.5.2 h44f6412_6
  run:
    - bzip2 >=1.0.8,<2.0a0
    - libgcc-ng >=12
    - libxml2 >=2.11.3,<2.12.0a0
    - libzlib >=1.2.13,<1.3.0a0
    - lz4-c >=1.9.3,<1.10.0a0
    - lzo >=2.10,<3.0a0
    - openssl >=3.1.0,<4.0a0
    - xz >=5.2.6,<6.0a0
    - zstd >=1.5.2,<1.6.0a0
test:
  commands:
    - test -f "${PREFIX}/lib/pkgconfig/libarchive.pc"
    - test -f "${PREFIX}/include/archive.h"
    - test -f "${PREFIX}/include/archive_entry.h"
    - test -f "${PREFIX}/lib/libarchive.a"
    - test -f "${PREFIX}/lib/libarchive${SHLIB_EXT}"
    - bsdcat --version
    - bsdcpio --version
    - bsdtar --version
    - bsdtar -tf test/hello_world.xar
  files:
    - test/hello_world.xar
about:
  home: http://www.libarchive.org/
  license: BSD-2-Clause
  license_family: BSD
  license_file: COPYING
  summary: Multi-format archive and compression library
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - ocefpaf
