# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Aug 22 14:56:40 2023
# ------------------------------------------------

package:
  name: libsolv
  version: 0.7.24
source:
  fn: libsolv-0.7.24.tar.gz
  patches:
    - conda_variant_priorization.patch
    - no_error_subdir_mismatch.patch
  sha256: 62743265222a729c7fe94c40f7b90ccc1ac5568f5ee6df46884e7ce3c16c78c7
  url: https://github.com/openSUSE/libsolv/archive/0.7.24.tar.gz
build:
  number: '3'
  run_exports:
    - libsolv >=0.7.24,<0.8.0a0
  string: hd84c7bf_3
requirements:
  build:
    - _openmp_mutex 4.5 2_gnu
    - _sysroot_linux-aarch64_curr_repodata_hack 4 h57d6b7b_13
    - binutils_impl_linux-aarch64 2.40 h870a726_0
    - binutils_linux-aarch64 2.40 h94bbfa1_1
    - bzip2 1.0.8 hf897c2e_4
    - c-ares 1.19.1 h31becfc_0
    - ca-certificates 2023.7.22 hcefe29a_0
    - cmake 3.26.4 hef020d8_0
    - expat 2.5.0 hd600fc2_1
    - gcc_impl_linux-aarch64 12.3.0 hcde2664_0
    - gcc_linux-aarch64 12.3.0 h464a8f7_1
    - gxx_impl_linux-aarch64 12.3.0 hcde2664_0
    - gxx_linux-aarch64 12.3.0 h21accf6_1
    - kernel-headers_linux-aarch64 4.18.0 h5b4a56d_13
    - keyutils 1.6.1 h4e544f5_0
    - krb5 1.21.2 hc419048_0
    - ld_impl_linux-aarch64 2.40 h2d8c526_0
    - libcurl 8.2.1 h4e8248e_0
    - libedit 3.1.20191231 he28a2e2_2
    - libev 4.33 h516909a_1
    - libexpat 2.5.0 hd600fc2_1
    - libgcc-devel_linux-aarch64 12.3.0 h8b5ab12_0
    - libgcc-ng 13.1.0 h2b4548d_0
    - libgomp 13.1.0 h2b4548d_0
    - libnghttp2 1.52.0 h250e5c5_0
    - libsanitizer 12.3.0 h8ebda82_0
    - libssh2 1.11.0 h492db2e_0
    - libstdcxx-devel_linux-aarch64 12.3.0 h8b5ab12_0
    - libstdcxx-ng 13.1.0 h452befe_0
    - libuv 1.44.2 h31becfc_1
    - libzlib 1.2.13 h31becfc_5
    - make 4.3 h309ac5b_1
    - ncurses 6.4 h2e1726e_0
    - openssl 3.1.2 h31becfc_0
    - rhash 1.4.3 h31becfc_1
    - sysroot_linux-aarch64 2.17 h5b4a56d_13
    - xz 5.2.6 h9cdd2b7_0
    - zlib 1.2.13 h31becfc_5
    - zstd 1.5.2 h4c53e97_7
  host:
    - _openmp_mutex 4.5 2_gnu
    - libgcc-ng 13.1.0 h2b4548d_0
    - libgomp 13.1.0 h2b4548d_0
    - libstdcxx-ng 13.1.0 h452befe_0
    - libzlib 1.2.13 h31becfc_5
    - zlib 1.2.13 h31becfc_5
  run:
    - libgcc-ng >=12
    - libstdcxx-ng >=12
    - libzlib >=1.2.13,<1.3.0a0
about:
  description: libsolv, a free package dependency solver using a satisfiability algorithm.
  dev_url: https://github.com/openSUSE/libsolv
  home: https://github.com/openSUSE/libsolv
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.BSD
  summary: Library for solving packages and reading repositories
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - AntoinePrv
    - JohanMabille
    - SylvainCorlay
    - adriendelsalle
    - davidbrochart
    - pavelzw
    - wolfv
