# This file created by conda-build 3.25.0
# ------------------------------------------------

package:
  name: libsolv
  version: 0.7.25
source:
  fn: libsolv-0.7.25.tar.gz
  patches:
    - conda_variant_priorization.patch
    - no_error_subdir_mismatch.patch
  sha256: b382bba4196b19c36eb34e0ef02546c0b922be601c6f73390c9ab643895b656a
  url: https://github.com/openSUSE/libsolv/archive/0.7.25.tar.gz
build:
  noarch: false
  noarch_python: false
  number: '0'
  string: hd84c7bf_0
requirements:
  build:
    - _openmp_mutex 4.5 2_gnu
    - _sysroot_linux-aarch64_curr_repodata_hack 4 h57d6b7b_13
    - binutils_impl_linux-aarch64 2.40 h870a726_0
    - binutils_linux-aarch64 2.40 h94bbfa1_2
    - bzip2 1.0.8 hf897c2e_4
    - c-ares 1.19.1 h31becfc_0
    - ca-certificates 2023.7.22 hcefe29a_0
    - cmake 3.27.6 hef020d8_0
    - gcc_impl_linux-aarch64 12.3.0 hcde2664_2
    - gcc_linux-aarch64 12.3.0 h464a8f7_2
    - gxx_impl_linux-aarch64 12.3.0 hcde2664_2
    - gxx_linux-aarch64 12.3.0 h21accf6_2
    - kernel-headers_linux-aarch64 4.18.0 h5b4a56d_13
    - keyutils 1.6.1 h4e544f5_0
    - krb5 1.21.2 hc419048_0
    - ld_impl_linux-aarch64 2.40 h2d8c526_0
    - libcurl 8.3.0 h4e8248e_0
    - libedit 3.1.20191231 he28a2e2_2
    - libev 4.33 h516909a_1
    - libexpat 2.5.0 hd600fc2_1
    - libgcc-devel_linux-aarch64 12.3.0 h8b5ab12_2
    - libgcc-ng 13.2.0 hf8544c7_2
    - libgomp 13.2.0 hf8544c7_2
    - libnghttp2 1.52.0 h250e5c5_0
    - libsanitizer 12.3.0 h8ebda82_2
    - libssh2 1.11.0 h492db2e_0
    - libstdcxx-devel_linux-aarch64 12.3.0 h8b5ab12_2
    - libstdcxx-ng 13.2.0 h9a76618_2
    - libuv 1.46.0 h31becfc_0
    - libzlib 1.2.13 h31becfc_5
    - ncurses 6.4 h2e1726e_0
    - ninja 1.11.1 hdd96247_0
    - openssl 3.1.3 h31becfc_0
    - rhash 1.4.4 h31becfc_0
    - sysroot_linux-aarch64 2.17 h5b4a56d_13
    - xz 5.2.6 h9cdd2b7_0
    - zstd 1.5.5 h4c53e97_0
  host:
    - _openmp_mutex 4.5 2_gnu
    - libgcc-ng 13.2.0 hf8544c7_2
    - libgomp 13.2.0 hf8544c7_2
    - libstdcxx-ng 13.2.0 h9a76618_2
    - libzlib 1.2.13 h31becfc_5
    - zlib 1.2.13 h31becfc_5
  run:
    - libgcc-ng >=12
    - libstdcxx-ng >=12
    - libzlib >=1.2.13,<1.3.0a0
test:
  commands:
    - test -f "${PREFIX}/lib/libsolv${SHLIB_EXT}"
    - test -f "${PREFIX}/lib/libsolvext${SHLIB_EXT}"
    - test -f "${PREFIX}/lib/libsolv.so.1"
    - test -f "${PREFIX}/include/solv/repo.h"
    - dumpsolv -h
    - cmake -G Ninja -S test/ -B build/ -D LIB_NAME="libsolv${SHLIB_EXT}" ${CMAKE_ARGS}
    - cmake --build build/
    - cmake --build build --target test
  files:
    - test/*
  requires:
    - cmake
    - gcc_linux-aarch64 12.*
    - gxx_linux-aarch64 12.*
    - ninja
about:
  description: libsolv, a free package dependency solver using a satisfiability algorithm.
  dev_url: https://github.com/openSUSE/libsolv
  home: https://github.com/openSUSE/libsolv
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.BSD
  summary: Library for solving packages and reading repositories
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - AntoinePrv
    - JohanMabille
    - SylvainCorlay
    - adriendelsalle
    - davidbrochart
    - pavelzw
    - wolfv
