# This file created by conda-build 3.24.0
# ------------------------------------------------

package:
  name: libnghttp2
  version: 1.58.0
source:
  sha256: 9ebdfbfbca164ef72bdf5fd2a94a4e6dfb54ec39d2ef249aeb750a91ae361dfb
  url: https://github.com/nghttp2/nghttp2/releases/download/v1.58.0/nghttp2-1.58.0.tar.gz
build:
  number: 0
  run_exports:
    - libnghttp2 >=1.58.0,<2.0a0
  string: hb0e430d_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - _sysroot_linux-aarch64_curr_repodata_hack 4 h57d6b7b_13
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_impl_linux-aarch64 2.40 h40ea8b1_0
    - binutils_linux-aarch64 2.40 h19b5abf_2
    - gcc_impl_linux-64 12.3.0 he2b93b0_2
    - gcc_impl_linux-aarch64 12.3.0 hfb0b921_2
    - gcc_linux-aarch64 12.3.0 hd570763_2
    - gxx_impl_linux-64 12.3.0 he2b93b0_2
    - gxx_impl_linux-aarch64 12.3.0 hfb0b921_2
    - gxx_linux-aarch64 12.3.0 h4913bc6_2
    - kernel-headers_linux-64 2.6.32 he073ed8_16
    - kernel-headers_linux-aarch64 4.18.0 h5b4a56d_13
    - ld_impl_linux-64 2.40 h41732ed_0
    - ld_impl_linux-aarch64 2.40 hc365e21_0
    - libgcc-devel_linux-64 12.3.0 h8bca6fd_2
    - libgcc-devel_linux-aarch64 12.3.0 h1a07b91_2
    - libgcc-ng 13.2.0 h807b86a_2
    - libgomp 13.2.0 h807b86a_2
    - libsanitizer 12.3.0 h0f45ef3_2
    - libstdcxx-devel_linux-64 12.3.0 h8bca6fd_2
    - libstdcxx-devel_linux-aarch64 12.3.0 h1a07b91_2
    - libstdcxx-ng 13.2.0 h7e041cc_2
    - make 4.3 hd18ef5c_1
    - sysroot_linux-64 2.12 he073ed8_16
    - sysroot_linux-aarch64 2.17 h5b4a56d_13
  host:
    - _openmp_mutex 4.5 2_gnu
    - c-ares 1.21.0 h31becfc_0
    - ca-certificates 2023.7.22 hcefe29a_0
    - libev 4.33 h516909a_1
    - libgcc-ng 13.2.0 hf8544c7_2
    - libgomp 13.2.0 hf8544c7_2
    - libstdcxx-ng 13.2.0 h9a76618_2
    - libzlib 1.2.13 h31becfc_5
    - openssl 3.1.4 h31becfc_0
    - zlib 1.2.13 h31becfc_5
  run:
    - c-ares >=1.21.0,<2.0a0
    - libev >=4.33,<4.34.0a0
    - libgcc-ng >=12
    - libstdcxx-ng >=12
    - libzlib >=1.2.13,<1.3.0a0
    - openssl >=3.1.4,<4.0a0
test:
  commands:
    - nghttp -nv https://nghttp2.org
    - test ! -f ${PREFIX}/lib/libnghttp2.a
    - test -f ${PREFIX}/lib/libnghttp2.so
about:
  description: 'This is an implementation of the Hypertext Transfer Protocol version
    2 in C.


    The framing layer of HTTP/2 is implemented as a reusable C library. On top

    of that, we have implemented an HTTP/2 client, server and proxy. We have

    also developed load test and benchmarking tools for HTTP/2.

    '
  dev_url: https://github.com/nghttp2/nghttp2
  doc_url: https://nghttp2.org/documentation/
  home: http://github.com/nghttp2/nghttp2
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: This is an implementation of Hypertext Transfer Protocol version 2.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - cpaulik
    - mariusvniekerk
    - wolfv
