# This file created by conda-build 3.25.0
# ------------------------------------------------

package:
  name: libarchive
  version: 3.7.2
source:
  patches:
    - patches/0001-Add-lib-to-CMAKE_FIND_LIBRARY_PREFIXES-for-lzma.patch
    - patches/0003-VC9-compatibility-test-for-BCryptDeriveKeyPBKDF2.patch
    - patches/0004-VC9-compatibility-define-BCRYPT_SUCCESS.patch
    - patches/0006-VC-openssl-define-inline-as-__inline.patch
    - patches/0007-CMake-VC9-compatibility-ignore-some-warnings.patch
  sha256: 63b40acff57467f7d3a64981d4bcff60b52f539fae7688aaaaee27a448b10266
  url: https://github.com/libarchive/libarchive/archive/v3.7.2.tar.gz
build:
  number: 0
  run_exports:
    - libarchive >=3.7.2,<3.8.0a0
  string: h566b526_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - _sysroot_linux-aarch64_curr_repodata_hack 4 h57d6b7b_13
    - autoconf 2.71 pl5321h2b4cb7a_1
    - automake 1.16.5 pl5321ha770c72_0
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_impl_linux-aarch64 2.40 h40ea8b1_0
    - binutils_linux-aarch64 2.40 h19b5abf_1
    - gcc_impl_linux-64 12.3.0 he2b93b0_0
    - gcc_impl_linux-aarch64 12.3.0 hfb0b921_0
    - gcc_linux-aarch64 12.3.0 hd570763_1
    - kernel-headers_linux-64 2.6.32 he073ed8_16
    - kernel-headers_linux-aarch64 4.18.0 h5b4a56d_13
    - ld_impl_linux-64 2.40 h41732ed_0
    - ld_impl_linux-aarch64 2.40 hc365e21_0
    - libgcc-devel_linux-64 12.3.0 h8bca6fd_0
    - libgcc-devel_linux-aarch64 12.3.0 h1a07b91_0
    - libgcc-ng 13.2.0 h807b86a_0
    - libgomp 13.2.0 h807b86a_0
    - libnsl 2.0.0 h7f98852_0
    - libsanitizer 12.3.0 h0f45ef3_0
    - libstdcxx-ng 13.2.0 h7e041cc_0
    - libtool 2.4.7 h27087fc_0
    - m4 1.4.18 h516909a_1001
    - make 4.3 hd18ef5c_1
    - perl 5.32.1 4_hd590300_perl5
    - pkg-config 0.29.2 h36c2ea0_1008
    - sysroot_linux-64 2.12 he073ed8_16
    - sysroot_linux-aarch64 2.17 h5b4a56d_13
  host:
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hf897c2e_4
    - ca-certificates 2023.7.22 hcefe29a_0
    - icu 73.2 h787c7f5_0
    - libgcc-ng 13.2.0 hf8544c7_0
    - libgomp 13.2.0 hf8544c7_0
    - libiconv 1.17 h9cdd2b7_0
    - libstdcxx-ng 13.2.0 h9a76618_0
    - libxml2 2.11.5 h3091e33_1
    - libzlib 1.2.13 h31becfc_5
    - lz4-c 1.9.3 h01db608_1
    - lzo 2.10 h516909a_1000
    - openssl 3.1.2 h31becfc_0
    - xz 5.2.6 h9cdd2b7_0
    - zlib 1.2.13 h31becfc_5
    - zstd 1.5.5 h4c53e97_0
  run:
    - bzip2 >=1.0.8,<2.0a0
    - libgcc-ng >=12
    - libxml2 >=2.11.5,<2.12.0a0
    - libzlib >=1.2.13,<1.3.0a0
    - lz4-c >=1.9.3,<1.10.0a0
    - lzo >=2.10,<3.0a0
    - openssl >=3.1.2,<4.0a0
    - xz >=5.2.6,<6.0a0
    - zstd >=1.5.5,<1.6.0a0
test:
  commands:
    - test -f "${PREFIX}/lib/pkgconfig/libarchive.pc"
    - test -f "${PREFIX}/include/archive.h"
    - test -f "${PREFIX}/include/archive_entry.h"
    - test -f "${PREFIX}/lib/libarchive.a"
    - test -f "${PREFIX}/lib/libarchive${SHLIB_EXT}"
    - bsdcat --version
    - bsdcpio --version
    - bsdtar --version
    - bsdtar -tf test/hello_world.xar
  files:
    - test/hello_world.xar
about:
  home: http://www.libarchive.org/
  license: BSD-2-Clause
  license_family: BSD
  license_file: COPYING
  summary: Multi-format archive and compression library
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - ocefpaf
