# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Dec  7 11:30:44 2022
# ------------------------------------------------

package:
  name: ruamel.yaml.clib
  version: 0.2.7
source:
  sha256: 1f08fd5a2bea9c4180db71678e850b995d2a5f4537be0e94557668cf0f5f9497
  url: https://pypi.io/packages/source/r/ruamel.yaml.clib/ruamel.yaml.clib-0.2.7.tar.gz
build:
  number: '1'
  script: /home/conda/feedstock_root/build_artifacts/ruamel.yaml.clib_1670412745210/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
    -m pip install . -vv
  string: py310hb89b984_1
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.39 he00db2b_1
    - binutils_impl_linux-aarch64 2.39 h57c828d_1
    - binutils_linux-aarch64 2.39 h9a81858_11
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2022.9.24 ha878542_0
    - cross-python_linux-aarch64 3.10 33_cpython
    - crossenv 1.2.0 pyhd8ed1ab_8
    - gcc_impl_linux-64 11.3.0 hab1b70f_19
    - gcc_impl_linux-aarch64 11.3.0 hb41bcec_19
    - gcc_linux-aarch64 11.3.0 h148fe96_11
    - kernel-headers_linux-64 2.6.32 he073ed8_15
    - kernel-headers_linux-aarch64 4.18.0 h5b4a56d_13
    - ld_impl_linux-64 2.39 hcc3a1bd_1
    - ld_impl_linux-aarch64 2.39 hc438fd5_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-devel_linux-64 11.3.0 h210ce93_19
    - libgcc-devel_linux-aarch64 11.3.0 h191a13f_19
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libiconv 1.17 h166bdaf_0
    - libnsl 2.0.0 h7f98852_0
    - libsanitizer 11.3.0 h239ccf8_19
    - libsqlite 3.40.0 h753d276_0
    - libstdcxx-ng 12.2.0 h46fd767_19
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.13 h166bdaf_4
    - lz4-c 1.9.3 h9c3ff4c_1
    - ncurses 6.3 h27087fc_1
    - openssl 3.0.7 h0b41bf4_1
    - popt 1.16 h0b475e3_2002
    - python 3.10.8 h4a9ceb5_0_cpython
    - readline 8.1.2 h0f457ee_0
    - rsync 3.2.7 h70740c4_0
    - sed 4.8 he412f7d_0
    - sysroot_linux-64 2.12 he073ed8_15
    - sysroot_linux-aarch64 2.17 h43d7e78_13
    - tk 8.6.12 h27826a3_0
    - tzdata 2022g h191b570_0
    - xxhash 0.8.0 h7f98852_3
    - xz 5.2.6 h166bdaf_0
    - zstd 1.5.2 h6239696_4
  host:
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hf897c2e_4
    - ca-certificates 2022.9.24 h4fd8a4c_0
    - ld_impl_linux-aarch64 2.39 h16cd69b_1
    - libffi 3.4.2 h3557bc0_5
    - libgcc-ng 12.2.0 h607ecd0_19
    - libgomp 12.2.0 h607ecd0_19
    - libnsl 2.0.0 hf897c2e_0
    - libsqlite 3.40.0 hf9034f9_0
    - libuuid 2.32.1 hf897c2e_1000
    - libzlib 1.2.13 h4e544f5_4
    - ncurses 6.3 headf329_1
    - openssl 3.0.7 hb4cce97_1
    - pip 22.3.1 pyhd8ed1ab_0
    - python 3.10.8 hac3cb69_0_cpython
    - readline 8.1.2 h38e3740_0
    - setuptools 65.5.1 pyhd8ed1ab_0
    - tk 8.6.12 hd8af866_0
    - tzdata 2022g h191b570_0
    - wheel 0.38.4 pyhd8ed1ab_0
    - xz 5.2.6 h9cdd2b7_0
  run:
    - libgcc-ng >=12
    - python >=3.10,<3.11.0a0
    - python >=3.10,<3.11.0a0 *_cpython
    - python_abi 3.10.* *_cp310
test:
  commands:
    - python -c "from importlib.util import find_spec; assert find_spec('_ruamel_yaml')"
  downstreams:
    - ruamel.yaml
about:
  home: https://sourceforge.net/projects/ruamel-yaml-clib/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: C version of reader, parser and emitter for ruamel.yaml derived from libyaml
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - mbargull
    - ocefpaf
