# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Aug 17 16:29:02 2020
# ------------------------------------------------

package:
    name: lzo
    version: '2.10'
source:
    sha256: c0f892943208266f9b6543b3ae308fab6284c5c90e627931446fb49b4221a072
    url: http://www.oberhumer.com/opensource/lzo/download/lzo-2.10.tar.gz
build:
    number: '1000'
    run_exports:
        - lzo >=2.10,<3.0a0
    string: h516909a_1000
requirements:
    build:
        - _openmp_mutex 4.5 1_gnu
        - binutils_impl_linux-aarch64 2.34 hb77b82c_9
        - binutils_linux-aarch64 2.34 hfcdf779_27
        - bzip2 1.0.8 h516909a_2
        - c-ares 1.16.1 h516909a_0
        - ca-certificates 2020.6.20 hecda079_0
        - cmake 3.18.0 h5c55442_0
        - expat 2.2.9 h4c5d2ac_2
        - gcc_impl_linux-aarch64 7.5.0 hf17dfc6_14
        - gcc_linux-aarch64 7.5.0 h6232204_27
        - kernel-headers_linux-aarch64 4.18.0 hca5cc2b_10
        - krb5 1.17.1 h09dc549_2
        - ld_impl_linux-aarch64 2.34 h281f86e_9
        - libcurl 7.71.1 hcdd3856_4
        - libedit 3.1.20191231 he28a2e2_2
        - libev 4.33 h516909a_0
        - libgcc-devel_linux-aarch64 7.5.0 h1a28f53_14
        - libgcc-ng 9.3.0 h8e86211_15
        - libgomp 9.3.0 h8e86211_15
        - libnghttp2 1.41.0 hab1572f_1
        - libssh2 1.9.0 hab1572f_5
        - libstdcxx-ng 9.3.0 hca8aa85_15
        - libuv 1.38.0 h516909a_0
        - make 4.3 h516909a_0
        - ncurses 6.2 he1b5a44_1
        - openssl 1.1.1g h516909a_1
        - rhash 1.3.6 h14c3975_1001
        - sysroot_linux-aarch64 2.17 h4744778_10
        - tk 8.6.10 hed695b0_0
        - xz 5.2.5 h6dd45c4_1
        - zlib 1.2.11 h516909a_1007
    host:
        - _openmp_mutex 4.5 1_gnu
        - libgcc-ng 9.3.0 h8e86211_15
        - libgomp 9.3.0 h8e86211_15
    run:
        - libgcc-ng >=7.5.0
test:
    commands:
        - test -f ${PREFIX}/include/lzo/lzoconf.h
        - test -f ${PREFIX}/lib/liblzo2.a
        - test -f ${PREFIX}/lib/liblzo2${SHLIB_EXT}
about:
    description: 'LZO offers pretty fast compression and extremely fast decompression.

        MiniLZO is a very lightweight subset of the LZO library.

        '
    home: http://www.oberhumer.com/opensource/lzo/
    license: GPL v2+
    license_family: GPL2
    license_file: COPYING
    summary: LZO is a portable lossless data compression library written in ANSI C.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - rmax
