# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Sep 27 16:14:15 2021
# ------------------------------------------------

package:
  name: jsonpatch
  version: '1.32'
source:
  fn: jsonpatch-1.32.tar.gz
  sha256: b6ddfe6c3db30d81a96aaeceb6baf916094ffa23d7dd5fa2c13e13f8b6e600c2
  url: https://pypi.org/packages/source/j/jsonpatch/jsonpatch-1.32.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/jsonpatch_1632759296524/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . --no-deps -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2021.5.30 ha878542_0
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libffi 3.4.2 h9c3ff4c_4
    - libgcc-ng 11.2.0 h1d223b6_8
    - libgomp 11.2.0 h1d223b6_8
    - libstdcxx-ng 11.2.0 he4da1e4_8
    - ncurses 6.2 h58526e2_4
    - openssl 1.1.1l h7f98852_0
    - pip 21.2.4 pyhd8ed1ab_0
    - python 3.9.7 hb7a2778_2_cpython
    - python_abi 3.9 2_cp39
    - readline 8.1 h46c0cb4_0
    - setuptools 58.0.4 py39hf3d152e_2
    - sqlite 3.36.0 h9cd32fc_2
    - tk 8.6.11 h27826a3_1
    - tzdata 2021a he74cb21_1
    - wheel 0.37.0 pyhd8ed1ab_1
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
  run:
    - jsonpointer >=1.9
    - python >=3.6
test:
  imports:
    - jsonpatch
about:
  dev_url: https://github.com/stefankoegl/python-json-patch
  doc_url: https://python-json-patch.readthedocs.io/en/latest/
  home: https://github.com/stefankoegl/python-json-patch
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: Apply JSON-Patches (RFC 6902)
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - anguslees
    - pmlandwehr
