# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Apr 12 22:02:18 2023
# ------------------------------------------------

package:
  name: packaging
  version: '23.1'
source:
  sha256: a392980d2b6cffa644431898be54b0045151319d1e7ec34f0cfed48767dd334f
  url: https://pypi.io/packages/source/p/packaging/packaging-23.1.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/packaging_1681337016113/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . --no-deps -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - brotlipy 0.7.0 py311hd4cff14_1005
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2022.12.7 ha878542_0
    - certifi 2022.12.7 pyhd8ed1ab_0
    - cffi 1.15.1 py311h409f033_3
    - charset-normalizer 3.1.0 pyhd8ed1ab_0
    - cryptography 40.0.1 py311h9b4c7bb_0
    - docutils 0.19 py311h38be061_1
    - flit 3.8.0 pyhd8ed1ab_0
    - flit-core 3.8.0 pyhd8ed1ab_0
    - idna 3.4 pyhd8ed1ab_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.40.0 h753d276_0
    - libuuid 2.38.1 h0b41bf4_0
    - libzlib 1.2.13 h166bdaf_4
    - ncurses 6.3 h27087fc_1
    - openssl 3.1.0 h0b41bf4_0
    - pip 23.0.1 pyhd8ed1ab_0
    - pycparser 2.21 pyhd8ed1ab_0
    - pyopenssl 23.1.1 pyhd8ed1ab_0
    - pysocks 1.7.1 pyha2e5f31_6
    - python 3.11.3 h2755cc3_0_cpython
    - python_abi 3.11 3_cp311
    - readline 8.2 h8228510_1
    - requests 2.28.2 pyhd8ed1ab_1
    - setuptools 67.6.1 pyhd8ed1ab_0
    - tk 8.6.12 h27826a3_0
    - tomli-w 1.0.0 pyhd8ed1ab_0
    - tzdata 2023c h71feb2d_0
    - urllib3 1.26.15 pyhd8ed1ab_0
    - wheel 0.40.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.7
test:
  commands:
    - pip check
  imports:
    - packaging
  requires:
    - pip
about:
  home: https://github.com/pypa/packaging
  license: Apache-2.0
  license_file: LICENSE
  summary: Core utilities for Python packages
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - nicoddemus
