# This file created by conda-build 3.25.0
# ------------------------------------------------

package:
  name: yaml-cpp
  version: 0.8.0
source:
  sha256: fbe74bbdcee21d656715688706da3c8becfd946d92cd44705cc6098bb23b3a16
  url: https://github.com/jbeder/yaml-cpp/archive/refs/tags/0.8.0.tar.gz
build:
  number: 0
  run_exports:
    - yaml-cpp >=0.8.0,<0.9.0a0
  string: h2f0025b_0
requirements:
  build:
    - _openmp_mutex 4.5 2_gnu
    - _sysroot_linux-aarch64_curr_repodata_hack 4 h57d6b7b_13
    - binutils_impl_linux-aarch64 2.40 h870a726_0
    - binutils_linux-aarch64 2.40 h94bbfa1_2
    - bzip2 1.0.8 hf897c2e_4
    - c-ares 1.19.1 h31becfc_0
    - ca-certificates 2023.7.22 hcefe29a_0
    - cmake 3.27.6 hef020d8_0
    - gcc_impl_linux-aarch64 12.3.0 hcde2664_2
    - gcc_linux-aarch64 12.3.0 h464a8f7_2
    - gxx_impl_linux-aarch64 12.3.0 hcde2664_2
    - gxx_linux-aarch64 12.3.0 h21accf6_2
    - kernel-headers_linux-aarch64 4.18.0 h5b4a56d_13
    - keyutils 1.6.1 h4e544f5_0
    - krb5 1.21.2 hc419048_0
    - ld_impl_linux-aarch64 2.40 h2d8c526_0
    - libcurl 8.3.0 h4e8248e_0
    - libedit 3.1.20191231 he28a2e2_2
    - libev 4.33 h516909a_1
    - libexpat 2.5.0 hd600fc2_1
    - libgcc-devel_linux-aarch64 12.3.0 h8b5ab12_2
    - libgcc-ng 13.2.0 hf8544c7_2
    - libgomp 13.2.0 hf8544c7_2
    - libnghttp2 1.52.0 h250e5c5_0
    - libsanitizer 12.3.0 h8ebda82_2
    - libssh2 1.11.0 h492db2e_0
    - libstdcxx-devel_linux-aarch64 12.3.0 h8b5ab12_2
    - libstdcxx-ng 13.2.0 h9a76618_2
    - libuv 1.46.0 h31becfc_0
    - libzlib 1.2.13 h31becfc_5
    - ncurses 6.4 h2e1726e_0
    - ninja 1.11.1 hdd96247_0
    - openssl 3.1.3 h31becfc_0
    - rhash 1.4.4 h31becfc_0
    - sysroot_linux-aarch64 2.17 h5b4a56d_13
    - xz 5.2.6 h9cdd2b7_0
    - zstd 1.5.5 h4c53e97_0
  host:
    - _openmp_mutex 4.5 2_gnu
    - libgcc-ng 13.2.0 hf8544c7_2
    - libgomp 13.2.0 hf8544c7_2
    - libstdcxx-ng 13.2.0 h9a76618_2
  run:
    - libgcc-ng >=12
    - libstdcxx-ng >=12
test:
  commands:
    - test -f "${PREFIX}/lib/libyaml-cpp${SHLIB_EXT}"
    - test ! -f "${PREFIX}/lib/libyaml-cpp.a"
    - test -f "${PREFIX}/lib/cmake/yaml-cpp/yaml-cpp-config.cmake"
    - cmake -G Ninja -S test/ -B build-test/ ${CMAKE_ARGS}
    - cmake --build build-test/
    - cmake --build build-test/ --target test
  files:
    - test/
  requires:
    - cmake
    - gcc_linux-aarch64 12.*
    - gxx_linux-aarch64 12.*
    - ninja
about:
  dev_url: https://github.com/jbeder/yaml-cpp
  doc_url: https://github.com/jbeder/yaml-cpp/wiki/Tutorial
  home: https://github.com/jbeder/yaml-cpp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: yaml-cpp is a YAML parser and emitter in C++ matching the YAML 1.2 spec.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - AntoinePrv
    - allanleal
    - marcelotrevisani
    - seanyen
    - tadeu
    - wolfv
