# This file created by conda-build 3.24.0
# ------------------------------------------------

package:
  name: libzlib
  version: 1.2.13
source:
  sha256: b3a24de97a8fdbc835b9833169501030b8977031bcb54b3b3ac13740f846ab30
  url:
    - http://zlib.net/zlib-1.2.13.tar.gz
    - https://gnupg.org/ftp/gcrypt/zlib/zlib-1.2.13.tar.gz
build:
  number: 5
  run_exports:
    - libzlib >=1.2.13,<1.3.0a0
  string: h31becfc_5
requirements:
  build:
    - _openmp_mutex 4.5 2_gnu
    - _sysroot_linux-aarch64_curr_repodata_hack 4 h57d6b7b_13
    - binutils_impl_linux-aarch64 2.40 h870a726_0
    - binutils_linux-aarch64 2.40 h94bbfa1_0
    - gcc_impl_linux-aarch64 12.3.0 hcde2664_0
    - gcc_linux-aarch64 12.3.0 h464a8f7_0
    - kernel-headers_linux-aarch64 4.18.0 h5b4a56d_13
    - ld_impl_linux-aarch64 2.40 h2d8c526_0
    - libgcc-devel_linux-aarch64 12.3.0 h8b5ab12_0
    - libgcc-ng 13.1.0 h2b4548d_0
    - libgomp 13.1.0 h2b4548d_0
    - libsanitizer 12.3.0 h8ebda82_0
    - libstdcxx-ng 13.1.0 h452befe_0
    - sysroot_linux-aarch64 2.17 h5b4a56d_13
  host:
    - _openmp_mutex 4.5 2_gnu
    - libgcc-ng 13.1.0 h2b4548d_0
    - libgomp 13.1.0 h2b4548d_0
  run:
    - libgcc-ng >=12
  run_constrained:
    - zlib 1.2.13 *_5
test:
  commands:
    - test ! -f ${PREFIX}/lib/libz.a
    - test ! -f ${PREFIX}/lib/libz${SHLIB_EXT}
    - test ! -f ${PREFIX}/include/zlib.h
about:
  description: 'zlib is designed to be a free, general-purpose, lossless data-compression

    library for use on virtually any computer hardware and operating system.

    '
  dev_url: https://github.com/madler/zlib
  doc_url: http://zlib.net/manual.html
  home: http://zlib.net/
  license: Zlib
  license_family: Other
  license_file: license.txt
  summary: Massively spiffy yet delicately unobtrusive compression library
extra:
  copy_test_source_files: true
  feedstock-name: zlib
  final: true
  recipe-maintainers:
    - groutr
    - isuruf
    - msarahan
    - ocefpaf
