# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Aug 12 23:22:52 2022
# ------------------------------------------------

package:
  name: xz
  version: 5.2.6
source:
  patches:
    - 0001-Add-vs2008-support-via-cmake.patch
    - 0002-Add-gettimeofday-for-VS2008.patch
  sha256: 13e3402e301b6018f6a71ef0e497f714c6d11e214ae82dab156b81c2a64acb25
  url: http://downloads.sourceforge.net/project/lzmautils/xz-5.2.6.tar.bz2
build:
  number: '0'
  run_exports:
    - xz >=5.2.6,<6.0a0
  string: h9cdd2b7_0
requirements:
  build:
    - _openmp_mutex 4.5 2_gnu
    - autoconf 2.69 pl5321h689fa9f_11
    - automake 1.16.5 pl5321h8af1aa0_0
    - binutils_impl_linux-aarch64 2.36.1 h026399b_2
    - binutils_linux-aarch64 2.36 h7854541_10
    - gcc_impl_linux-aarch64 10.4.0 hbc23e19_16
    - gcc_linux-aarch64 10.4.0 h72ad2ee_10
    - kernel-headers_linux-aarch64 4.18.0 h5b4a56d_13
    - ld_impl_linux-aarch64 2.36.1 h02ad14f_2
    - libgcc-devel_linux-aarch64 10.4.0 hf691355_16
    - libgcc-ng 12.1.0 h3242a24_16
    - libgomp 12.1.0 h3242a24_16
    - libnsl 2.0.0 hf897c2e_0
    - libsanitizer 10.4.0 h69a60c7_16
    - libstdcxx-ng 12.1.0 hd01590b_16
    - libtool 2.4.6 h01db608_1008
    - m4 1.4.18 h516909a_1001
    - make 4.3 h309ac5b_1
    - perl 5.32.1 2_hf897c2e_perl5
    - sysroot_linux-aarch64 2.17 h43d7e78_13
  host:
    - _openmp_mutex 4.5 2_gnu
    - libgcc-ng 12.1.0 h3242a24_16
    - libgomp 12.1.0 h3242a24_16
  run:
    - libgcc-ng >=12
about:
  description: 'XZ Utils is free general-purpose data compression software with a
    high

    compression ratio. XZ Utils were written for POSIX-like systems, but also

    work on some not-so-POSIX systems.

    '
  dev_url: http://git.tukaani.org/
  doc_source_url: https://github.com/xz-mirror/xz/blob/master/README
  doc_url: http://tukaani.org/xz/
  home: http://tukaani.org/xz/
  license: LGPL-2.1 and GPL-2.0
  license_file: COPYING
  summary: Data compression software with high compression ratio
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - mingwandroid
    - msarahan
    - nehaljwani
    - ocefpaf
    - scopatz
