# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Jul 19 18:01:58 2023
# ------------------------------------------------

package:
  name: urllib3
  version: 2.0.4
source:
  sha256: 8d22f86aae8ef5e410d4f539fde9ce6b2113a001bb4d189e0aed70642d602b11
  url: https://pypi.io/packages/source/u/urllib3/urllib3-2.0.4.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/urllib3_1689789803562/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2023.5.7 hbcca054_0
    - editables 0.3 pyhd8ed1ab_0
    - hatchling 1.18.0 pyhd8ed1ab_0
    - importlib-metadata 6.8.0 pyha770c72_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.1.0 he5830b7_0
    - libgomp 13.1.0 he5830b7_0
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.42.0 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 hcb278e6_0
    - openssl 3.1.1 hd590300_1
    - packaging 23.1 pyhd8ed1ab_0
    - pathspec 0.11.1 pyhd8ed1ab_0
    - pip 23.2 pyhd8ed1ab_0
    - pluggy 1.2.0 pyhd8ed1ab_0
    - python 3.11.4 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 68.0.0 pyhd8ed1ab_0
    - tk 8.6.12 h27826a3_0
    - tomli 2.0.1 pyhd8ed1ab_0
    - trove-classifiers 2023.7.6 pyhd8ed1ab_0
    - tzdata 2023c h71feb2d_0
    - wheel 0.40.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
    - zipp 3.16.2 pyhd8ed1ab_0
  run:
    - brotli-python >=1.0.9
    - pysocks >=1.5.6,<2.0,!=1.5.7
    - python >=3.7
test:
  commands:
    - pip check
  imports:
    - urllib3
    - urllib3.contrib
    - urllib3.util
  requires:
    - pip
about:
  dev_url: https://github.com/shazow/urllib3
  doc_url: https://urllib3.readthedocs.io/
  home: https://urllib3.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: HTTP library with thread-safe connection pooling, file post, and more.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ocefpaf
    - sethmlarson
    - shazow
