# This file created by conda-build 3.24.0
# ------------------------------------------------

package:
  name: libgcc-ng
  version: 13.1.0
source:
  - patches:
      - patches/0021-Hardcode-HAVE_ALIGNED_ALLOC-1-in-libstdc-v3-configur.patch
      - patches/new-allow-commands-in-main-specfile.patch
    sha256: bacd4c614d8bd5983404585e53478d467a254249e0f1bb747c8bc6d787bd4fa2
    url: https://ftp.gnu.org/gnu/gcc/gcc-13.1.0/gcc-13.1.0.tar.gz
build:
  detect_binary_files_with_prefix: false
  ignore_run_exports:
    - __glibc
  missing_dso_whitelist:
    - '*'
  number: 0
  rpaths_patcher: patchelf
  string: h2b4548d_0
requirements:
  build:
    - _sysroot_linux-aarch64_curr_repodata_hack 4 h57d6b7b_13
    - binutils_impl_linux-aarch64 2.39 h57c828d_1
    - gcc_bootstrap_linux-64 12.2.0 hba5b598_13
    - gcc_impl_linux-aarch64 13.1.0.*
    - gfortran_impl_linux-aarch64 13.1.0.*
    - gxx_impl_linux-aarch64 13.1.0.*
    - kernel-headers_linux-aarch64 4.18.0 h5b4a56d_13
    - ld_impl_linux-aarch64 2.39 hc438fd5_1
    - sysroot_linux-aarch64 2.17 h5b4a56d_13
  host:
    - _openmp_mutex 4.5 2_gnu
    - _sysroot_linux-aarch64_curr_repodata_hack 4 h57d6b7b_13
    - kernel-headers_linux-aarch64 4.18.0 h5b4a56d_13
    - libgomp 13.1.0 h2b4548d_0
    - sysroot_linux-aarch64 2.17 h5b4a56d_13
  run:
    - _openmp_mutex >=4.5
  run_constrained:
    - libgomp 13.1.0 h2b4548d_0
test:
  commands:
    - test -f ${PREFIX}/lib/libgcc_s.so
    - test -f ${PREFIX}/lib/libgomp.so.1
    - test `readlink ${PREFIX}/lib/libgomp.so.1` == "libgomp.so.1.0.0"
  requires:
    - sysroot_linux-aarch64
about:
  home: https://gcc.gnu.org/onlinedocs/gccint/Libgcc.html
  license: GPL-3.0-only WITH GCC-exception-3.1
  summary: The GCC low-level runtime library
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - beckermr
    - isuruf
    - timsnyder
    - xhochy
