# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Jan 26 09:54:45 2023
# ------------------------------------------------

package:
  name: lz4-c
  version: 1.9.4
source:
  sha256: 0b0e3aa07c8c063ddf40b082bdf7e37a1562bda40a0ff5272957f3e987e0e54b
  url: https://github.com/lz4/lz4/archive/v1.9.4.tar.gz
build:
  number: '0'
  run_exports:
    - lz4-c >=1.9.4,<1.10.0a0
  string: hd600fc2_0
requirements:
  build:
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-aarch64 2.39 h48546ad_1
    - binutils_linux-aarch64 2.39 h489c705_11
    - gcc_impl_linux-aarch64 11.3.0 h771ed3b_19
    - gcc_linux-aarch64 11.3.0 h2cafa97_11
    - gxx_impl_linux-aarch64 11.3.0 h771ed3b_19
    - gxx_linux-aarch64 11.3.0 h7ccc656_11
    - kernel-headers_linux-aarch64 4.18.0 h5b4a56d_13
    - ld_impl_linux-aarch64 2.39 h16cd69b_1
    - libgcc-devel_linux-aarch64 11.3.0 h02014c4_19
    - libgcc-ng 12.2.0 h607ecd0_19
    - libgomp 12.2.0 h607ecd0_19
    - libsanitizer 11.3.0 hdddb281_19
    - libstdcxx-devel_linux-aarch64 11.3.0 h02014c4_19
    - libstdcxx-ng 12.2.0 hc13a102_19
    - make 4.3 h309ac5b_1
    - patch 2.7.6 hf897c2e_1002
    - sysroot_linux-aarch64 2.17 h43d7e78_13
  host:
    - _openmp_mutex 4.5 2_gnu
    - libgcc-ng 12.2.0 h607ecd0_19
    - libgomp 12.2.0 h607ecd0_19
    - libstdcxx-ng 12.2.0 hc13a102_19
  run:
    - libgcc-ng >=12
    - libstdcxx-ng >=12
about:
  description: 'LZ4 is lossless compression algorithm, providing compression speed
    at 400

    MB/s per core (0.16 Bytes/cycle). It features an extremely fast decoder,

    with speed in multiple GB/s per core (0.71 Bytes/cycle). A high compression

    derivative, called LZ4_HC, is available, trading customizable CPU time for

    compression ratio. LZ4 library is provided as open source software using a

    BSD license.

    '
  home: https://www.lz4.org
  license: BSD-2-Clause
  license_file: lib/LICENSE
  summary: Extremely Fast Compression algorithm
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - mingwandroid
    - rmax
    - wesm
    - xhochy
