BUILD: aarch64-conda_cos7-linux-gnu
CI: azure
c_compiler: gcc
c_compiler_version: '10'
cdt_arch: aarch64
cdt_name: cos7
channel_sources: conda-forge
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: gxx
docker_image: quay.io/condaforge/linux-anvil-aarch64
extend_keys:
- extend_keys
- ignore_version
- ignore_build_only_deps
- pin_run_as_build
fortran_compiler: gfortran
ignore_build_only_deps:
- python
- numpy
libffi: '3.4'
lua: '5'
numpy: '1.16'
openssl: 1.1.1
perl: 5.26.2
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
python: 3.10.* *_cpython
r_base: '3.5'
target_platform: linux-aarch64
