# This file created by conda-build 3.24.0
# ------------------------------------------------

package:
  name: libssh2
  version: 1.11.0
source:
  sha256: 3736161e41e2693324deb38c26cfdc3efe6209d634ba4258db1cecff6a5ad461
  url: https://www.libssh2.org/download/libssh2-1.11.0.tar.gz
build:
  number: 0
  run_exports:
    - libssh2 >=1.11.0,<2.0a0
  string: h492db2e_0
requirements:
  build:
    - _openmp_mutex 4.5 2_gnu
    - _sysroot_linux-aarch64_curr_repodata_hack 4 h57d6b7b_13
    - binutils_impl_linux-aarch64 2.39 h48546ad_1
    - binutils_linux-aarch64 2.39 h489c705_13
    - cmake-no-system 3.18.0 hd600fc2_0
    - gcc_impl_linux-aarch64 12.2.0 h0c671d3_19
    - gcc_linux-aarch64 12.2.0 h9f724d2_13
    - kernel-headers_linux-aarch64 4.18.0 h5b4a56d_13
    - ld_impl_linux-aarch64 2.39 h16cd69b_1
    - libgcc-devel_linux-aarch64 12.2.0 h58a5bb6_19
    - libgcc-ng 13.1.0 h2b4548d_0
    - libgomp 13.1.0 h2b4548d_0
    - libsanitizer 12.2.0 hc13a102_19
    - libstdcxx-ng 13.1.0 h452befe_0
    - make 4.3 h309ac5b_1
    - sysroot_linux-aarch64 2.17 h5b4a56d_13
  host:
    - _openmp_mutex 4.5 2_gnu
    - ca-certificates 2023.5.7 hcefe29a_0
    - libgcc-ng 13.1.0 h2b4548d_0
    - libgomp 13.1.0 h2b4548d_0
    - libzlib 1.2.13 h4e544f5_4
    - openssl 3.1.1 h31becfc_1
    - zlib 1.2.13 h4e544f5_4
  run:
    - libgcc-ng >=12
    - libzlib >=1.2.13,<1.3.0a0
    - openssl >=3.1.1,<4.0a0
test:
  commands:
    - test -f $PREFIX/include/libssh2.h
    - test -f $PREFIX/include/libssh2_publickey.h
    - test -f $PREFIX/include/libssh2_sftp.h
    - test ! -f $PREFIX/lib/libssh2.a
    - test -f $PREFIX/lib/libssh2${SHLIB_EXT}
about:
  description: 'libssh2 is a library implementing the SSH2 protocol, available under
    the revised BSD license.

    '
  dev_url: https://github.com/libssh2/libssh2
  home: https://www.libssh2.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: the SSH library
extra:
  copy_test_source_files: true
  feedstock-name: libssh2
  final: true
  recipe-maintainers:
    - nehaljwani
    - ocefpaf
    - shadowwalkersb
    - xhochy
