# This file created by conda-build 3.23.3
# ------------------------------------------------

package:
  name: libnghttp2
  version: 1.52.0
source:
  sha256: 9877caa62bd72dde1331da38ce039dadb049817a01c3bdee809da15b754771b8
  url: https://github.com/nghttp2/nghttp2/releases/download/v1.52.0/nghttp2-1.52.0.tar.gz
build:
  number: 0
  run_exports:
    - libnghttp2 >=1.52.0,<2.0a0
  string: h250e5c5_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_impl_linux-aarch64 2.39 h57c828d_1
    - binutils_linux-aarch64 2.39 h9a81858_11
    - gcc_impl_linux-64 11.3.0 hab1b70f_19
    - gcc_impl_linux-aarch64 11.3.0 hb41bcec_19
    - gcc_linux-aarch64 11.3.0 h148fe96_11
    - gxx_impl_linux-64 11.3.0 hab1b70f_19
    - gxx_impl_linux-aarch64 11.3.0 hb41bcec_19
    - gxx_linux-aarch64 11.3.0 h85fa074_11
    - kernel-headers_linux-64 2.6.32 he073ed8_15
    - kernel-headers_linux-aarch64 4.18.0 h5b4a56d_13
    - ld_impl_linux-64 2.40 h41732ed_0
    - ld_impl_linux-aarch64 2.39 hc438fd5_1
    - libgcc-devel_linux-64 11.3.0 h210ce93_19
    - libgcc-devel_linux-aarch64 11.3.0 h191a13f_19
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libsanitizer 11.3.0 h239ccf8_19
    - libstdcxx-devel_linux-64 11.3.0 h210ce93_19
    - libstdcxx-devel_linux-aarch64 11.3.0 h191a13f_19
    - libstdcxx-ng 12.2.0 h46fd767_19
    - make 4.3 hd18ef5c_1
    - sysroot_linux-64 2.12 he073ed8_15
    - sysroot_linux-aarch64 2.17 h43d7e78_13
  host:
    - _openmp_mutex 4.5 2_gnu
    - c-ares 1.18.1 hf897c2e_0
    - ca-certificates 2022.12.7 h4fd8a4c_0
    - libev 4.33 h516909a_1
    - libgcc-ng 12.2.0 h607ecd0_19
    - libgomp 12.2.0 h607ecd0_19
    - libstdcxx-ng 12.2.0 hc13a102_19
    - libzlib 1.2.13 h4e544f5_4
    - openssl 3.0.8 hb4cce97_0
    - zlib 1.2.13 h4e544f5_4
  run:
    - c-ares >=1.18.1,<2.0a0
    - libev >=4.33,<4.34.0a0
    - libgcc-ng >=12
    - libstdcxx-ng >=12
    - libzlib >=1.2.13,<1.3.0a0
    - openssl >=3.0.8,<4.0a0
test:
  commands:
    - nghttp -nv https://nghttp2.org
    - test ! -f ${PREFIX}/lib/libnghttp2.a
    - test -f ${PREFIX}/lib/libnghttp2.so
about:
  description: 'This is an implementation of the Hypertext Transfer Protocol version
    2 in C.


    The framing layer of HTTP/2 is implemented as a reusable C library. On top

    of that, we have implemented an HTTP/2 client, server and proxy. We have

    also developed load test and benchmarking tools for HTTP/2.

    '
  dev_url: https://github.com/nghttp2/nghttp2
  doc_url: https://nghttp2.org/documentation/
  home: http://github.com/nghttp2/nghttp2
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: This is an implementation of Hypertext Transfer Protocol version 2.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - cpaulik
    - mariusvniekerk
    - wolfv
